# Generated by Django 3.2 on 2021-04-26 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=400)),
                ('imag', models.ImageField(upload_to='images/profile/')),
                ('phone', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('imag1', models.ImageField(blank=True, null=True, upload_to='images/pets')),
                ('imag2', models.ImageField(blank=True, null=True, upload_to='images/pets')),
                ('imag3', models.ImageField(blank=True, null=True, upload_to='images/pets')),
                ('imag4', models.ImageField(blank=True, null=True, upload_to='images/pets')),
                ('imag5', models.ImageField(blank=True, null=True, upload_to='images/pets')),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('fish', 'Fish'), ('hamster', 'Hamster'), ('lizard', 'Lizart'), ('snake', 'Snake')], default='dog', max_length=200)),
                ('age', models.CharField(choices=[('Baby (0 - 12 months)', 'Baby (0 - 12 months)'), ('Young (12 - 30 months)', 'Young (12 - 30 months)'), ('Medium (30-60 months)', 'Medium (30-60 months)'), ('Old (60-90 months)', 'Old (60-90 months)')], default='Baby (0 - 12 months)', max_length=50)),
                ('de_rasa', models.BooleanField(default=False)),
                ('take_care', models.CharField(choices=[('Eazy', 'Eazy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Eazy', max_length=100)),
                ('size', models.CharField(choices=[('Small ( < 1 kg)', 'Small ( < 1 kg)'), ('Medium ( < 3 kg)', 'Medium ( < 3 kg)'), ('Big ( > 3 kg)', 'Big ( > 3 kg)')], default='Small ( < 1 kg)', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('condition', models.IntegerField(default=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptedPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.pet')),
            ],
        ),
    ]
