# Generated by Django 3.2 on 2021-04-26 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_alter_adoptedpets_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptedpets',
            name='owner',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptedpets',
            name='adopter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to=settings.AUTH_USER_MODEL),
        ),
    ]
