# Generated by Django 3.2 on 2021-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20210426_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media',
            field=models.CharField(default='https://www.facebook.com/dragutu.matei', max_length=80),
            preserve_default=False,
        ),
    ]
