# Generated by Django 3.2 on 2021-04-28 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0004_profile_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptedpets',
            name='adopter',
        ),
        migrations.AddField(
            model_name='adoptedpets',
            name='adopter',
            field=models.ManyToManyField(related_name='adopter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='adoptedpets',
            name='owner',
        ),
        migrations.AddField(
            model_name='adoptedpets',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
